apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    camel.apache.org/integration: lab
    app.kubernetes.io/runtime: camel
  name: lab
spec:
  selector:
    matchLabels:
      camel.apache.org/integration: lab
  template:
    metadata:
      labels:
        camel.apache.org/integration: lab
    spec:
      containers:
      - image: lab:1.0-SNAPSHOT
        name: lab
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    camel.apache.org/integration: lab
    app.kubernetes.io/runtime: camel
  name: lab
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    camel.apache.org/integration: lab
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lab
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: lab
